### ISSUE TITLE
Any plans to support 7z?

### ISSUE THREAD

**Issue by mattalxndr** [althonos/fs.archive#4]
Any plans to support 7z?

**Comment by althonos** [comment]
None so far, but I guess it could be feasible with [`py7zr`](https://pypi.org/project/py7zr/).

**Comment by althonos** [comment]
I have added a new reader/writer for 7z based on `py7zr` in `v0.7.0`. Install the `7z` extra, and `open_archive` will be able to read and write 7z archives, even if they are password-protected.

**Comment by mattalxndr** [comment]
I'm picking this up right now. Looks great!!
